architecture-beta
    group cloud(cloud)[Rete Anycast]
    group fw1(server)[Firewall 1] in cloud
    group fw2(server)[Firewall 2] in cloud

    service server(server)[Upstream]
    service fscloud(internet)[FlashStart Cloud]
    service ds1(server)[Downstream 1] in fw1
    service ds2(server)[Downstream 2] in fw1
    service ds3(server)[Downstream 3] in fw2

    fscloud:T -- B:server
    server:R -- L:ds1
    server:R -- L:ds3
    server:R -- L:ds2
